import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Providers from './context/Providers'
import Header from './components/Header'
import Footer from './components/Footer'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

const roboto = Roboto({
  weight: ['100', '300', '400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body className={`text-dark dark:text-light ${roboto.className}`}>
        <Providers>
          <Header />
          {/* fixed header with h-24 */}
          <main className='mt-24'>{children}</main>
          <ToastContainer position='bottom-right' />
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
